"use strict";

const globals = require("globals");

const sharedRules = {
  "constructor-super": "error",
  "for-direction": "error",
  "getter-return": "error",
  "no-async-promise-executor": "error",
  "no-case-declarations": "error",
  "no-class-assign": "error",
  "no-compare-neg-zero": "error",
  "no-cond-assign": ["error", "except-parens"],
  "no-const-assign": "error",
  "no-constant-binary-expression": "error",
  "no-debugger": "warn",
  "no-dupe-args": "error",
  "no-dupe-class-members": "error",
  "no-dupe-else-if": "error",
  "no-dupe-keys": "error",
  "no-duplicate-case": "error",
  "no-empty-character-class": "error",
  "no-empty-pattern": "error",
  "no-eval": "error",
  "no-ex-assign": "error",
  "no-extra-boolean-cast": "error",
  "no-fallthrough": "error",
  "no-func-assign": "error",
  "no-implied-eval": "error",
  "no-import-assign": "error",
  "no-invalid-regexp": "error",
  "no-irregular-whitespace": "error",
  "no-loss-of-precision": "error",
  "no-new-func": "error",
  "no-new-native-nonconstructor": "error",
  "no-obj-calls": "error",
  "no-promise-executor-return": "error",
  "no-prototype-builtins": "error",
  "no-self-assign": "error",
  "no-setter-return": "error",
  "no-shadow-restricted-names": "error",
  "no-sparse-arrays": "error",
  "no-this-before-super": "error",
  "no-undef": "error",
  "no-unexpected-multiline": "error",
  "no-unmodified-loop-condition": "warn",
  "no-unreachable": "error",
  "no-unreachable-loop": "error",
  "no-unsafe-finally": "error",
  "no-unsafe-negation": "error",
  "no-unsafe-optional-chaining": "error",
  "no-unused-labels": "error",
  "no-unused-private-class-members": "error",
  "no-unused-vars": [
    "warn",
    {
      argsIgnorePattern: "^_",
      caughtErrorsIgnorePattern: "^_",
      ignoreRestSiblings: true,
      varsIgnorePattern: "^_",
    },
  ],
  "no-useless-backreference": "error",
  "no-useless-catch": "error",
  "no-useless-escape": "warn",
  "no-var": "error",
  "no-with": "error",
  "prefer-const": "warn",
  eqeqeq: ["warn", "always", { null: "ignore" }],
  "use-isnan": "error",
  "valid-typeof": "error",
};

module.exports = [
  {
    ignores: [
      "node_modules/**",
      "data/**",
      "coverage/**",
      ".history/**",
      ".VSCodeCounter/**",
      "release/**",
      "release-slim/**",
      "release-web/**",
      "dist/**",
      "**/*.min.js",
    ],
  },
  {
    files: [
      "src/**/*.js",
      "desktop/**/*.js",
      "scripts/**/*.js",
      "build/**/*.cjs",
      "test/**/*.js",
      "*.js",
      "*.config.js",
      "ecosystem*.js",
    ],
    languageOptions: {
      ecmaVersion: "latest",
      sourceType: "commonjs",
      globals: globals.node,
    },
    linterOptions: {
      reportUnusedDisableDirectives: "warn",
    },
    rules: sharedRules,
  },
  {
    files: ["public/**/*.js"],
    languageOptions: {
      ecmaVersion: "latest",
      sourceType: "script",
      globals: globals.browser,
    },
    linterOptions: {
      reportUnusedDisableDirectives: "warn",
    },
    rules: sharedRules,
  },
  {
    files: ["test/**/*.js"],
    rules: {
      "no-console": "off",
    },
  },
];
